baseurl = "https://chrisclarkson.org" # Hostname (and path) to the root.
title = "Chris Clarkson" # Site title.
theme = "coder-portfolio" # Set the theme.
languagecode = "en" # The siteâ€™s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.

paginate = 20 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

[params] # theme parameters
    author = "Chris Clarkson" # Author's name.
    info = "Cloud Platform Security and Hardware Hacker" # Author's job title or info.
    description = "Chris Clarkson's personal website" # Site description.
    keywords = "blog,developer,personal,hacker,electronics,platform,AWS,Azure" # Site keywords.
    avatarurl = "images/chrisclarkson.jpg" # Contain the path of the optionnal avatar in the static folder.

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = true
    hideCopyright = false

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    snsShare = true # new add

    thumbnail = "images/tn.png" # default sns thumbnail

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/ClarksonCJ/"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/ClarksonCJ/"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/cjclarkson/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "posts"
[[menu.main]]
    name = "About"
    weight = 2
    url = "about"
[[menu.main]]
    name = "My Study"
    weight = 3
    url = "study"
[[menu.main]]
    name = "Projects"
    weight = 4
    url = "projects"
[[menu.main]]
    name = "Resources"
    weight = 5
    url = "resources"